name: Build Resume PDF

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Chromium dependencies (Ubuntu 24.04+ safe)
        shell: bash
        run: |
          sudo apt-get update
          # Выбираем libasound2t64 если он есть (Ubuntu 24.04), иначе libasound2
          if apt-cache show libasound2t64 >/dev/null 2>&1; then
            ASOUND=libasound2t64
          else
            ASOUND=libasound2
          fi
          sudo apt-get install -y \
            fonts-liberation \
            "$ASOUND" \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcairo2 \
            libdrm2 \
            libgbm1 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libpangocairo-1.0-0 \
            libpango-1.0-0 \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxext6 \
            libxfixes3 \
            libxkbcommon0 \
            libxrandr2 \
            xdg-utils

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install md-to-pdf
        run: npm i -g md-to-pdf

      - name: Build EN PDF
        run: |
          md-to-pdf resume-en.md \
            --stylesheet resume.css \
            --launch-options '{"args": ["--no-sandbox","--disable-setuid-sandbox"]}' \
            --pdf-options '{"format":"A4","margin":"18mm"}'
          mv resume-en.pdf resume.pdf
          ls -la

      - name: Upload PDF as artifact (fallback)
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf

      - name: Commit PDF back to repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add resume.pdf || true
          git commit -m "chore: update resume PDF" || echo "No changes"
          git push || echo "Push skipped (branch protection?)"
